name: Deploy Food Ordering App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to App Server via Bastion
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/appserver_key ubuntu@10.0.2.170 "
              cd ~/food-ordering-system &&
              git pull origin main &&
              cd backend &&
              npm install &&
              sudo systemctl restart foodapp &&
              echo Deployment completed successfully
            "
